### PR TITLE
add sidecarCleanup field

### PR DESCRIPTION
**Pull request by chinatsu**
Required for [Ginuudan](https://github.com/nais/ginuudan) to do its thing

### CODE REVIEW

**Review by ambientsound — CHANGES_REQUESTED** [review]
Perhaps cleaning up sidecars should always be on, instead of having it in the spec?

**Comment by chinatsu** [comment]
> Perhaps cleaning up sidecars should always be on, instead of having it in the spec?

I'm not 100% sure. I think an opt-out

**Comment by Kyrremann** [comment]
Tipper det er enklere å få med seg at noen trenger det, enn å overvåke hva som faktisk blir brukt.

**Comment by chinatsu** [comment]
I'm taking the liberty to close this and always set the annotation in naiserator: https://github.com/nais/naiserator/pull/280

**Pull request closed without merging**
